version: '1'
services:
  AuthAPI:
    build: ./FoodDelivery.Services.AuthAPI
    ports:
      - "8080:8080"

  CouponAPI:
    build: ./FoodDelivery.Services.CouponAPI
    ports:
      - "8080:8080"

  EmailAPI:
    build: ./FoodDelivery.Services.EmailAPI
    ports:
      - "8080:8080"

  OrderAPI:
    build: ./FoodDelivery.Services.OrderAPI
    ports:
      - "8080:8080"

  ProductAPI:
    build: ./FoodDelivery.Services.ProductAPI
    ports:
      - "8080:8080"
 
  RewardsAPI:
    build: ./FoodDelivery.Services.RewardsAPI
    ports:
      - "8080:8080"

  ShoppingCartAPI:
    build: ./FoodDelivery.Services.ShoppingCartAPI
    ports:
      - "8080:8080"

  WebApp:
    build: ./FoodDelivery.Web
    ports:
      - "8080:8080"

  gateway:
    build: ./FoodDelivery.GatewaySolution
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Puerto para comunicación de RabbitMQ
      - "15672:15672"  # Puerto para interfaz de administración de RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=eyndqlge
      - RABBITMQ_DEFAULT_PASS=UyIFsIiLOzs-mMv80Z-pS6KBGzNBYkHV
