services:
  authapi:
    build: ./FoodDelivery.Services.AuthAPI
    ports:
      - "7002:7002"

  couponapi:
    build: ./FoodDelivery.Services.CouponAPI
    ports:
      - "7001:7001"

  emailapi:
    build: ./FoodDelivery.Services.EmailAPI
    ports:
      - "7029:7029"

  orderapi:
    build: ./FoodDelivery.Services.OrderAPI
    ports:
      - "7004:7004"

  productapi:
    build: ./FoodDelivery.Services.ProductAPI
    ports:
      - "7000:7000"
 
  rewardsapi:
    build: ./FoodDelivery.Services.RewardsAPI
    ports:
      - "7187:7187"

  shoppingcartapi:
    build: ./FoodDelivery.Services.ShoppingCartAPI
    ports:
      - "7003:7003"

  webapp:
    build: ./FoodDelivery.Web
    ports:
      - "7231:7231"

  gateway:
    build: ./FoodDelivery.GatewaySolution
    ports:
      - "7777:7777"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=eyndqlge
      - RABBITMQ_DEFAULT_PASS=UyIFsIiLOzs-mMv80Z-pS6KBGzNBYkHV
